language: node_js

node_js:
  - "8"
  - "10"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  - ~/.yarn
  - ~/.cache

install: yarn

script:
  - yarn start -- --silent & yarn e2e

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: yarn build
      deploy:
        provider: npm
        email: $EMAIL_ADDRESS
        api_key: $AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
